source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ZengSir/douyuu_pods.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DouyuuApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DouyuuApp
  pod 'DouyuuBase', '~> 0.0.1'

end
